"""add_approval_workflow_models

Revision ID: 20b26ba734e7
Revises: 96592b2dae60
Create Date: 2025-12-25 22:18:16.483640

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20b26ba734e7"
down_revision: str | Sequence[str] | None = "96592b2dae60"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approval_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("reservation_id", sa.Integer(), nullable=False),
        sa.Column("approver_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("request_message", sa.Text(), nullable=True),
        sa.Column("response_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["approver_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reservation_id"),
    )
    op.create_index(
        op.f("ix_approval_requests_id"), "approval_requests", ["id"], unique=False
    )
    op.add_column(
        "resources",
        sa.Column(
            "requires_approval", sa.Boolean(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "resources", sa.Column("default_approver_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "resources", "users", ["default_approver_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "resources", type_="foreignkey")
    op.drop_column("resources", "default_approver_id")
    op.drop_column("resources", "requires_approval")
    op.drop_index(op.f("ix_approval_requests_id"), table_name="approval_requests")
    op.drop_table("approval_requests")
    # ### end Alembic commands ###
